from enum import Enum


class ResolutionGoal(str, Enum):
    WORK_COMMUTE = "WORK_COMMUTE"
    HIGHWAY_ANXIETY = "HIGHWAY_ANXIETY"
    LONGER_TRIPS = "LONGER_TRIPS"
    NIGHT_DRIVING = "NIGHT_DRIVING"
    VISIT_FAMILY = "VISIT_FAMILY"
    OTHER = "OTHER"


class DrivingExperience(str, Enum):
    NEW = "NEW"
    SOME = "SOME"
    EXPERIENCED = "EXPERIENCED"


class DrivingFrequency(str, Enum):
    DAILY = "DAILY"
    FEW_TIMES_WEEK = "FEW_TIMES_WEEK"
    OCCASIONALLY = "OCCASIONALLY"
    RARELY = "RARELY"


class StressTrigger(str, Enum):
    HEAVY_TRAFFIC = "HEAVY_TRAFFIC"
    HONKING = "HONKING"
    HIGHWAYS = "HIGHWAYS"
    NIGHT_DRIVING = "NIGHT_DRIVING"
    COMPLEX_INTERSECTIONS = "COMPLEX_INTERSECTIONS"
    CONSTRUCTION = "CONSTRUCTION"
    PEDESTRIAN_AREAS = "PEDESTRIAN_AREAS"


class CalmingPreference(str, Enum):
    CALMING_MUSIC = "CALMING_MUSIC"
    DEEP_BREATHING = "DEEP_BREATHING"
    TALKING = "TALKING"
    PULLING_OVER = "PULLING_OVER"
    SILENCE = "SILENCE"


class RouteType(str, Enum):
    FASTEST = "FASTEST"
    CALMEST = "CALMEST"


class EventType(str, Enum):
    STRESS_DETECTED = "STRESS_DETECTED"
    INTERVENTION = "INTERVENTION"
    REROUTE_OFFERED = "REROUTE_OFFERED"
    REROUTE_ACCEPTED = "REROUTE_ACCEPTED"
    VOICE_COMMAND = "VOICE_COMMAND"
    PULL_OVER_REQUESTED = "PULL_OVER_REQUESTED"
